language: node_js
sudo: false
cache:
  apt: true
  directories:
  - node_modules
node_js:
- '6'
branches:
  only:
  - esa
before_install:
- npm install
before_script:
- git config --global user.name 'llminatoll via Travis CI'
- git config --global user.email '22927920+llminatoll@users.noreply.github.com'
- rm -rf public
- git clone --depth=1 --branch=master https://github.com/llminatoll/llminatoll.github.io.git public
- pushd public
- git ls-files | xargs -I {} rm -rf {}
- popd
script:
- $(npm bin)/hexo generate
- cd public
- git add -A
- git commit -m 'Update'
- '[ "$TRAVIS_BRANCH" == "esa" ]'
- '[ $GH_TOKEN ]'
- 'git push --force https://$GH_TOKEN@github.com/llminatoll/llminatoll.github.io.git HEAD:master'
env:
  global:
  - GIT_COMMITTER_NAME=llminatoll-via-TravisCI
  - GIT_COMMITTER_EMAIL=22927920+llminatoll@users.noreply.github.com
  - GIT_AUTHOR_NAME=llminatoll-via-TravisCI
  - GIT_AUTHOR_EMAIL=22927920+llminatoll@users.noreply.github.com
  
