# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png

# language
language: en

# OGP
twitter: @webdesignManga
twitter_site: @webdesignManga
google_plus: https://plus.google.com/114796801803130321567
fb_admins: 
fb_app_id: 510667169264465
image: # og:image. Default: First image in the content
# Help: https://hexo.io/docs/helpers.html#open-graph